### ISSUE TITLE
Add install progress indicators

### ISSUE THREAD

**Issue by yahyaKacem** [zaggino/brackets-npm-registry#11]
Hi, when I'm installing/updating something I'll be waiting with no indicators that the install or update is being processed, maybe some spinners or progress bars.

**Comment by zaggino** [comment]
Hi @yahyaKacem , this is waiting for https://github.com/adobe/brackets/pull/10761

**Comment by zaggino** [comment]
fixed by https://github.com/zaggino/brackets-npm-registry/commit/47917ce764954644b171a34d2ca2edbcadfd304a
