### ISSUE TITLE
Mac install fails: Looking for main in /dist folder

### ISSUE THREAD

**Issue by davidwaterston** [zaggino/brackets-npm-registry#12]
I just tried installing this extension on a Mac (OSX Yosemite 10.10.2), Brackets Release 1.2 build 1.2.0-15697 (release 8f82e2a97), using the instructions in the README. The clone and npm install went smoothly but the extension shows in Extension Manager as in error with only a 'Remove' option.
Looking in the Dev Tools I see this error:

[Extension] failed to load /Users/David/Library/Application Support/Brackets/extensions/user/brackets-npm-registry - Module does not exist: file:///Users/David/Library/Application%20Support/Brackets/extensions/user/brackets-npm-registry/dist/main.js

The folder name 'Users/David/Library/Application%20Support/Brackets/extensions/user/brackets-npm-registry' is correct. main.js is in that folder and tries to require 'dist/main' but *that* folder ('dist') doesn't exist.

**Comment by zaggino** [comment]
`dist` folder is generated by `npm install` command, try running `npm install` again to be sure there're no errors. Alternatively, you can run `gulp build` inside the cloned folder to create the `dist` folder.

**Comment by davidwaterston** [comment]
Obvious now that you mention it... I didn't have Gulp installed on that machine and didn't realise it was required. Installed Gulp and reran the ```npm install``` and it installed properly.

**Comment by zaggino** [comment]
Do you mean you had to install `gulp` globally? With `npm install --global gulp-cli`?
I thought `npm install` should be able to execute local gulp without having it installed globally.

**Comment by davidwaterston** [comment]
Yes, the error was:
```
npm WARN cannot run in wd brackets-npm-registry@0.2.0 gulp build (wd=/Users/David/Library/Application Support/Brackets/extensions/user/brackets-npm-registry)
```
which is fairly common with npm - I didn't have permissions to run in that folder.
There are [a few workarounds](https://github.com/npm/npm/issues/3497) but installing Gulp globally was the easiest.

**Comment by zaggino** [comment]
Thanks for the info, I'll update the README
