### ISSUE TITLE
Text un-readable with dark theme

### ISSUE THREAD

**Issue by globexdesigns** [zaggino/brackets-npm-registry#21]
See screenshot:

![screen shot 2015-05-06 at 8 09 45 am](https://cloud.githubusercontent.com/assets/226640/7496115/2505971a-f3c7-11e4-83c9-4c3e0d1f420e.png)

**Comment by zaggino** [comment]
Fixed in `0.3.1`, self-update through the dialog should be working too so let me know if it doesn't please.

**Comment by globexdesigns** [comment]
Definitely, better. However, the title and descriptions are still un-readable.

![v2](https://cloud.githubusercontent.com/assets/226640/7508501/4692bca4-f436-11e4-9f2f-bcee6d029c36.png)

**Comment by zaggino** [comment]
Interesting, they were fine in my `Brackets Dark` theme ... Can you try `0.3.2` ? If doesn't work, what theme are you using?

**Comment by AdriVanHoudt** [comment]
I use quick dark https://github.com/cheesypoof/QuickDark and I get the same output as the original post

**Comment by globexdesigns** [comment]
Looking good in 0.3.2 for me! My theme was "Brackets Dark".

**Comment by zaggino** [comment]
@AdriVanHoudt latest version is fixed for your theme too.

**Comment by AdriVanHoudt** [comment]
Cool thanks!
