### ISSUE TITLE
ExpectedError: Error: Max connection attempts reached

### ISSUE THREAD

**Issue by ckoo7** [zaggino/brackets-npm-registry#24]
I am using this extension for brackets to use eslint extension. But after installing this m facing the problem 
![screenshot from 2015-08-03 17-55-29](https://cloud.githubusercontent.com/assets/8359963/9037427/e8131a7a-3a08-11e5-868a-9c81ab8f2617.png)

**Comment by zaggino** [comment]
Do you have any errors in the console?
Did the `npm install` finish without any errors?
Try running `gulp build` in the directory of this extension and make sure it passed.

**Comment by chandra92** [comment]
`npm install` and `gulp build` both finished successfully inside  `brackets-npm-registry` extension directory. I m seeing this error while creating any file with `.js` extension & an `es-lint` error also. 

![screenshot from 2015-08-04 14-08-23](https://cloud.githubusercontent.com/assets/8359963/9056662/4d75fe60-3ab2-11e5-86ad-fab9a2665d3b.png)

**Comment by chandra92** [comment]
![screenshot from 2015-08-04 14-13-02](https://cloud.githubusercontent.com/assets/8359963/9056772/f34b16ae-3ab2-11e5-9f5b-c540b96fcf2f.png)

**Comment by zaggino** [comment]
Any error in the brackets console? Debug -> Show developer tools -> Console
This connection problem is usually caused by failing extension.

**Comment by chandra92** [comment]
Now I just Uninstalled everything and re-installed `brackets-npm-registry`. Seeing this error in console: 

![screenshot from 2015-08-04 18-19-57](https://cloud.githubusercontent.com/assets/8359963/9060915/afc47358-3ad5-11e5-9ac1-047e869329c3.png)

**Comment by zaggino** [comment]
Can't see anything there. This is worth reading though:
https://github.com/zaggino/brackets-git/issues/1109
https://github.com/zaggino/brackets-git/issues/410
https://github.com/zaggino/brackets-git/issues/468

**Comment by chandra92** [comment]
Is this something wrong?? Got this error in brackets console while installing `zaggino.brackets.git`

`[node-log 3:47:06 PM] { [Error: ENOENT, no such file or directory '/home/chandra/.config/Brackets/cef_data/f_0001be']
  errno: 34,
  code: 'ENOENT',
  path: '/home/chandra/.config/Brackets/cef_data/f_0001be',
  syscall: 'open' } `

`Blind write attempted:  /home/chandra/.config/Brackets/state.json 1438769844000 null `

**Comment by zaggino** [comment]
I've never seen that one, did it install fine?

**Comment by chandra92** [comment]
Yes, installed successfully. And again I have installed all extensions from `brackets-npm-registry`. It seems to work fine now. I am not seeing any error any more.

**Comment by vkkotha** [comment]
I had the same issue recently and Killing Brackets.app/Contents/node-core process and restarting Brackets seems to fix this issue on my Mac.

**Comment by aparvezbd** [comment]
I have found the problem in console. How can I solve it?
![screenshot_1](https://cloud.githubusercontent.com/assets/11468491/21750590/f37adfae-d5e0-11e6-85dd-c4764bd9328f.png)
