### ISSUE TITLE
the extension didn't show on right

### ISSUE THREAD

**Issue by abnud1** [zaggino/brackets-npm-registry#25]
I have arch linux x64 with KDE plasma 5 and installed brackets from AUR, after following the installation instructions exactly the extension didn't show even after restarting brackets.  

My extensions folder : 
asgerf.bracket-rename  brackets-npm-registry enturn.quick-search mikaeljorhult.brackets-autoprefixer talmand.html-templates brackets-emmet camden.w3cvalidation fede91.brackets-preferences-ui quickdocsjs themesforbrackets brackets-morecsscodehints  dnbard.extensions-rating  hirse.beautify swmitra.html-designer

**Comment by zaggino** [comment]
Hi @abnud1 , can you copy ouput of your console (debug > show developer tools) after Brackets starts?

**Comment by abnud1** [comment]
this is the output http://pastebin.com/eNPyBhCi

I think the problem are these two errors in particular : 
Failed to load resource file:///home/abd/.config/Brackets/extensions/user/brackets-npm-registry/node_modules/babel-core/node_modules/core-js/client/shim.min.js
Failed to load resource file:///home/abd/.config/Brackets/extensions/user/brackets-npm-registry/node_modules/babel-core/node_modules/regenerator/runtime.js

well I noticed that ~/.config/Brackets/extensions/user/brackets-npm-registry/node_modules/babel-core/npm_modules folder doesn't exist

**Comment by zaggino** [comment]
@abnud1 are you using npm3 to install this by any chance?

**Comment by zaggino** [comment]
i've updated the extension, in case you were using npm3, delete the extension and try the install process again please

**Comment by abnud1** [comment]
thanks very much, it shows now but it takes forever to finishes downloading, is this normal ? I have ADSL 512 kbit connection.

**Comment by zaggino** [comment]
If the server is down, it builds its own registry file which takes a bit time for the first time. Should be fine next time.
