### ISSUE TITLE
Use lots of CPU and memory

### ISSUE THREAD

**Issue by eight04** [zaggino/brackets-npm-registry#26]
![](http://i.imgur.com/XJWyMD4.png)
It just hang my computer when brackets started. I have no idea what's going on. Is it updating?

**Comment by zaggino** [comment]
If heroku server is down, it actually tries to build the registry locally.

If you have never used `npm search` before, this might take time and be cpu extensive. On my pc it takes about 5 minutes for the first time and then about 10-15 seconds following times.

Url of the server is http://brackets-npm-registry.herokuapp.com/

Unfortunately, I don't have paid plan for it so it's not 100% stable.

**Comment by zaggino** [comment]
This is the "download method": https://github.com/zaggino/brackets-npm-registry/blob/8b17f771220a515c5fbf1830d943861e1da1d944/src/ui/registry-utils.js#L83-L100

You might want to remove the `return Promise.resolve(NpmDomain.exec('buildRegistry')` part if it causes too much problems to your computer.

**Comment by zaggino** [comment]
If you remove that, it'll of course mean that the extension will fail whenever the server is down for some reason beyond my control.

**Comment by eight04** [comment]
What will happen if the extension fails? I have installed [brackets-eslint](https://github.com/zaggino/brackets-eslint). Am I able to use it when server is down?

**Comment by zaggino** [comment]
Yes, you only need the server to load list of extensions and install stuff. Once the extension is installed it will work regardless of the server status.

**Comment by eight04** [comment]
Thanks for the reply :smile:
