### ISSUE TITLE
Not able to install extensions

### ISSUE THREAD

**Issue by pritin-tyagaraj** [zaggino/brackets-npm-registry#27]
I followed the instructions here (https://github.com/zaggino/brackets-npm-registry) and I can now see the list of extensions when I click on the 'npm' icon in the right toolbar. However, when I click on 'Install' on one of the extensions, I get this error:
![screen shot 2015-11-06 at 3 19 12 pm](https://cloud.githubusercontent.com/assets/5196657/10994098/0baded4e-849a-11e5-9473-5e6159ab908a.png)

Any pointers on where I went wrong? Thanks a lot.

**Comment by zaggino** [comment]
What OS are you on?

**Comment by zaggino** [comment]
Seems like the extension has problems creating a symlink: https://github.com/zaggino/brackets-npm-registry/blob/f724ba47d85947df254f66af94b45588e8cd5dd5/src/node/node-ensure.js#L30-L51

Do you have nodejs installed on your machine?

**Comment by pritin-tyagaraj** [comment]
Yes I do. `node -v` gives me `v4.2.2`

**Comment by zaggino** [comment]
What's the node's location? What does `which node` give you?
