### ISSUE TITLE
I can't find out how to install this.

### ISSUE THREAD

**Issue by Johannes5** [zaggino/brackets-npm-registry#29]
I need to install eslint and for that apparently I need npm registry.

Of course I have read the instructions, but unfortunately I can't make any sense of this:

sudo npm install --global gulp-cli
cd ~/Library/Application\ Support/Brackets/extensions/user/
git clone https://github.com/zaggino/brackets-npm-registry.git brackets-npm-registry
cd brackets-npm-registry
npm install

What is this supposed to tell me? I am missing something.

(I also tried it with the brackets extension manager, but it tells me that I need a newer version, but I already got 1.5.)

Hope you can help,

Johannes

**Comment by zaggino** [comment]
Hi, what OS are you using?
Just open a terminal and execute those commands line by line.

**Comment by Johannes5** [comment]
Thanks for answering so quickly!
I am using mac

Yes I actually thought of just copypasting it in my terminal.
but this rusulted in an error message:
![image](https://cloud.githubusercontent.com/assets/14299835/11653110/137daae4-9d9c-11e5-8664-90ae53a59409.png)

of course I've tried typing in my mac's password but that didn't help

**Comment by Johannes5** [comment]
Thank you!

**Comment by zaggino** [comment]
Instead of the first line, try just:
```
npm install gulp-cli
```

**Comment by Johannes5** [comment]
So I typed it in line by line and it seemed to work.
After I entered the 3rd line an installation window popped up and I installed something.

Then I typed in the 4rth line(cd brackets-npm-registry) and it told me "no such file or diretory"
And the 5th line didn't work either.
here is a screenshot of the terminal:
cd brackets-npm-registry
![image](https://cloud.githubusercontent.com/assets/14299835/11653665/f108abc2-9d9f-11e5-8b7b-8f73130a036c.png)

Then I looked back into the brackets extension manager and found out that I can just drag and drop the zip file of the extension. After I did that, npm registry was filed under "installed extensiones", which made me happy.
However there is no other sign if it being installed:
![image](https://cloud.githubusercontent.com/assets/14299835/11653722/51e96594-9da0-11e5-9faf-e63c03c019f8.png)

Hope you can help

**Comment by zaggino** [comment]
Google `install xcode on mac` as the error says after `git clone` command.

**Comment by zaggino** [comment]
You need to have those `command line developer tools` mentioned installed.

**Comment by Johannes5** [comment]
thanks for your help
everything works fine now

**Comment by zaggino** [comment]
:+1: cool
