### ISSUE TITLE
error [object object]

### ISSUE THREAD

**Issue by yahyaKacem** [zaggino/brackets-npm-registry#3]
Hi, tried to install brackets-eslint as you suggested in this [issue](https://github.com/zaggino/brackets-eslint/issues/1#issuecomment-84733263) but I get a window with title `Operation in progress...` and 

>ERROR
[object object]

**Comment by zaggino** [comment]
Hi, what OS do you have? Do you see the same error in console (F12)?

**Comment by mackenza** [comment]
I got this same error on eslint and hello world earlier today but a few hours ago I tried again and it worked. . I was at work when it failed so I thought it was related to the firewall so I didn't debug much. . Could the Heroku server have been down or something like that?

**Comment by zaggino** [comment]
If you're able to open the extension dialog with list of extensions in npm then it's not a heroku issue.

**Comment by zaggino** [comment]
And you wouldn't be able to get to the `Operation in progress...` if you couldn't open the list of extensions.

**Comment by Alxandr** [comment]
I have the same error.

Here is the console output:

![image](https://cloud.githubusercontent.com/assets/112334/6795461/5d2581d6-d1e0-11e4-8ccd-6814ce05c4af.png)

**Comment by Alxandr** [comment]
Some more info that might be useful:

![image](https://cloud.githubusercontent.com/assets/112334/6795517/38cbbc5a-d1e1-11e4-8ca8-b23305a17af5.png)

**Comment by zaggino** [comment]
Thanks @Alxandr , helped a lot - fixed in `0.1.2`

**Comment by zaggino** [comment]
Open a separate issue if you find more problems.

**Comment by zaggino** [comment]
The second screenshot says what I've thought, this doesn't work on Windows right now: #4
