### ISSUE TITLE
Issue and pull counts are always -1

### ISSUE THREAD

**Issue by petetnt** [zaggino/brackets-npm-registry#30]
It seems that the endpoint `https://github.com/${username}/${repo}/issues/counts` doesn't exist anymore, which makes the issue and pull counts stay `-1`.

The issue counts can be easily retrieved from `https://api.github.com/repos/zaggino/brackets-npm-registry` endpoint as `open_issues_cpunt` but it seems that there is no ready made way to get open PR's.

**Comment by zaggino** [comment]
What do you mean by

> there is no ready made way to get open PR's

?

**Comment by petetnt** [comment]
Oh, my thought was cut a bit short there:

I meant that there's no field in the response for the open PR count in neither the `repos`-endpoint or under `https://api.github.com/repos/zaggino/brackets-npm-registry/pulls` so you'd need to count them yourself (but I think that `pulls/` endpoint only shows the 30 newest pull requests so there's that). You could just load the page and get it from the Pull requests `.counter`-element though.
