### ISSUE TITLE
Unable to install extension.

### ISSUE THREAD

**Issue by ProfitWarning** [zaggino/brackets-npm-registry#33]
When I try to install a extension from the registry, I get the following error:
`ERROR: "ReferenceError: Promise is not defined\n    at /home/sysop/.config/Brackets/extensions/user/brackets-npm-registry/dist/node/node-ensure.js:84:14\n    at tryCatcher (/home/sysop/.config/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/home/sysop/.config/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/promise.js:507:31)\n    at Promise._settlePromiseAt (/home/sysop/.config/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/promise.js:581:18)\n    at Promise._settlePromises (/home/sysop/.config/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/promise.js:697:14)\n    at Async._drainQueue (/home/sysop/.config/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/async.js:123:16)\n    at Async._drainQueues (/home/sysop/.config/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/async.js:133:10)\n    at Async.drainQueues (/home/sysop/.config/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/async.js:15:14)\n    at process._tickCallback (node.js:415:13)"`

**Comment by Stingzor** [comment]
Same thing happening here;
Using Ubuntu 15.10, I'm also unable to reinstall the plugin

**Comment by anIddan** [comment]
I also have this issue heres the log:
`ERROR: "ReferenceError: Promise is not defined\n    at /Users/iddan/Library/Application Support/Brackets/extensions/user/brackets-npm-registry/dist/node/node-ensure.js:84:14\n    at tryCatcher (/Users/iddan/Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/Users/iddan/Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/promise.js:507:31)\n    at Promise._settlePromiseAt (/Users/iddan/Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/promise.js:581:18)\n    at Promise._settlePromises (/Users/iddan/Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/promise.js:697:14)\n    at Async._drainQueue (/Users/iddan/Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/async.js:123:16)\n    at Async._drainQueues (/Users/iddan/Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/async.js:133:10)\n    at Async.drainQueues (/Users/iddan/Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/async.js:15:14)\n    at process._tickCallback (node.js:415:13)"`
tried to format my MacBook, didn't help

**Comment by zaggino** [comment]
Sorry guys, this bug got into the latest version by mistake (Windows and Mac versions of Brackets have native promises, Linux version doesn't). Can you try again with now latest version 0.3.9?

**Comment by anIddan** [comment]
Still getting this on my MacBook with Mac OS X El Capitan:
`ERROR: "ReferenceError: Promise is not defined\n    at /Users/iddan/Library/Application Support/Brackets/extensions/user/brackets-npm-registry/dist/node/node-ensure.js:84:14\n    at tryCatcher (/Users/iddan/Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/Users/iddan/Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/promise.js:507:31)\n    at Promise._settlePromiseAt (/Users/iddan/Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/promise.js:581:18)\n    at Promise._settlePromises (/Users/iddan/Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/promise.js:697:14)\n    at Async._drainQueue (/Users/iddan/Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/async.js:123:16)\n    at Async._drainQueues (/Users/iddan/Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/async.js:133:10)\n    at Async.drainQueues (/Users/iddan/Library/Application Support/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/async.js:15:14)\n    at process._tickCallback (node.js:415:13)"`

**Comment by zaggino** [comment]
If you look at the file: https://github.com/zaggino/brackets-npm-registry/blob/master/src/node/node-ensure.js
It doesn't even include `Promise` anymore, try installing the latest version and don't forget to run `gulp build` in the extension directory.

**Comment by ProfitWarning** [comment]
I tried the latest version and get a differrent error now:
`ERROR: "TypeError: Cannot call method 'split' of undefined\n    at Object.exports.processEnvWithPath (/home/sysop/.config/Brackets/extensions/user/brackets-npm-registry/dist/node/utils.js:15:69)\n    at /home/sysop/.config/Brackets/extensions/user/brackets-npm-registry/dist/node/brackets-node-domain.js:88:20\n    at tryCatcher (/home/sysop/.config/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/home/sysop/.config/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/promise.js:507:31)\n    at Promise._settlePromiseAt (/home/sysop/.config/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/promise.js:581:18)\n    at Async._drainQueue (/home/sysop/.config/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/async.js:128:12)\n    at Async._drainQueues (/home/sysop/.config/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/async.js:133:10)\n    at Async.drainQueues (/home/sysop/.config/Brackets/extensions/user/brackets-npm-registry/node_modules/bluebird/js/main/async.js:15:14)\n    at process._tickCallback (node.js:415:13)"`

**Comment by zaggino** [comment]
Released `0.4.1` to fix `Cannot call method 'split' of undefined`

**Comment by ProfitWarning** [comment]
Works now!
Thanks.
