### ISSUE TITLE
registry returns 500

### ISSUE THREAD

**Issue by AdriVanHoudt** [zaggino/brackets-npm-registry#37]
on url https://brackets-npm-registry.herokuapp.com/registry

**Comment by zaggino** [comment]
:open_mouth:

**Comment by AdriVanHoudt** [comment]
Idd :P also my eslint is broken so I thought update brackets-eslint and then I found the registery was down :P

**Comment by zaggino** [comment]
I'll have to look into it ... seems like heroku has changed something because I definitely didn't ... I've restarted it for now, maybe it'll help.

**Comment by AdriVanHoudt** [comment]
Thanks!

**Comment by zaggino** [comment]
So Heroku added some new rules or npm grew too big ...
```
2016-04-07T12:07:58.943068+00:00 heroku[web.1]: Error R15 (Memory quota vastly exceeded)
2016-04-07T12:07:58.943068+00:00 heroku[web.1]: Stopping process with SIGKILL
2016-04-07T12:08:00.046108+00:00 heroku[web.1]: Process exited with status 137
```
When trying to build the registry...

**Comment by zaggino** [comment]
@AdriVanHoudt yay, should be up again -> https://brackets-npm-registry.herokuapp.com/registry
