### ISSUE TITLE
can we please have a nicer icon?

### ISSUE THREAD

**Issue by catdad** [zaggino/brackets-npm-registry#38]
The Brackets sidebar icons #BBBBBB (187 for all 3 rgb values), and the NPM icon is white with a dark gray border. It looks out of place.

At the very least, changing the CSS to include a brightness filter would be better, as such:

```css
-webkit-filter: grayscale(100%) brightness(80%);
```

However, getting a better icon that fits the style of Brackets more would be good. I would be willing to make one if you are on board.

**Comment by zaggino** [comment]
Submit a PR with whatever solution you prefer, I don't have a much of design feeling.
I think I just "stole" the current icon from the npm website when I was implementing this.

**Comment by catdad** [comment]
Awesome. I will try to put something together this weekend.
