### ISSUE TITLE
Warnings on install 

### ISSUE THREAD

**Issue by meeple142** [zaggino/brackets-npm-registry#43]
System Info 
- window 7
- node v6.6.0
- npm 3.10.3
- git version 2.7.2.windows.1

followed instructions in [README.md ](https://github.com/zaggino/brackets-npm-registry/blob/master/README.md#windows )and got the following errors
![image](https://cloud.githubusercontent.com/assets/10274976/20543380/0f9f7fb6-b0c3-11e6-92ad-90be6ca40e53.png)

just text
````
npm WARN deprecated babel-core@5.8.25: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated cross-spawn-async@1.0.1: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
````
and at the end after the dependency tree (probably from running windows not mac)
````
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
````

**Comment by zaggino** [comment]
Hi, know about these. So far there has been no reason to update dependencies and potentially introduce bugs. Is the registry working for you?

**Comment by meeple142** [comment]
Thanks for the quick reply. Everything seems to be working fine. Just wanted to make sure that you knew about the deprecations. 
Also sorry for not being friendly in my initial post. I have got in a habit of being as quick as possible with issues for my own projects and didn't stop and think to be human. 
Thank you for all of your great work with Brackets!
Josh
