### ISSUE TITLE
still having error [object object] when trying to install brackets-eslint on ubuntu

### ISSUE THREAD

**Issue by yahyaKacem** [zaggino/brackets-npm-registry#5]
Hi, I'm using:

    - Ubuntu 14.04
    - Brackets Release 1.2 experimental build 1.2.0-15697 (release 8f82e2a97)

I did what you said in the #3 and updated to latest version of this plugin through npm since it gave me the same error when I tried to update through the GUI update worked but when I tried to install the brackets-eslint I get the same error with this message in console:

![error](https://cloud.githubusercontent.com/assets/844900/6799668/1cf4b73e-d218-11e4-9ae1-11c3d315eeb7.png)

**Comment by zaggino** [comment]
Hi @yahyaKacem , you need to re-install this extension, self-updating doesn't work yet.
Use these steps (delete the current brackets-npm-directory): https://github.com/zaggino/brackets-npm-registry#linux
The error in console should change.

**Comment by zaggino** [comment]
@yahyaKacem do you have node.js installed on your linux?

**Comment by yahyaKacem** [comment]
yes, I have node v0.12.0 installed through nvm.
the new error is this:
![error2](https://cloud.githubusercontent.com/assets/844900/6801772/2cf2df5e-d22b-11e4-8b1b-0ed9ff6aa662.png)

**Comment by zaggino** [comment]
can you let me know where your node executable is when installing with nvm? seems like extension is not able to find your node

**Comment by zaggino** [comment]
`which node` should return some path

**Comment by yahyaKacem** [comment]
node path:

    /home/yahya/.nvm/v0.12.0/bin/node

**Comment by yahyaKacem** [comment]
I think an option to set the node path is a better solution here don't you think?
I'm using nvm because sometimes I get some tools that are not compatibale with the current version of node so I downgrade to v0.11 or v0.10 so an option to set the node path is a better solution here.  
Also the path for the v0.12 in my Ubuntu 14.04 is this: `/home/yahya/.nvm/versions/node/v0.12.0/bin/node` but for my Ubuntu 12.04 is `/home/yahya/.nvm/v0.12.0/bin/node`.

**Comment by zaggino** [comment]
Extension looks for node in system path and then some predefined paths, but I'll have to implement the ability to set your custom path it seems.

**Comment by zaggino** [comment]
Available in the latest version `0.1.3`, please test if you'll have some time.
![image](https://cloud.githubusercontent.com/assets/1067319/6819140/7f564ad4-d310-11e4-9510-796e3ac53034.png)

**Comment by zaggino** [comment]
Closed as the above issue has been resolved with a new feature.

**Comment by zaggino** [comment]
update, found a better way to handle this so above screenshot is actually deprecated after a few hours ... everything should now work without setting the node path, extension will link to the node executable which is included with Brackets
